drop table user if exists;
create table user (
    id bigint generated by default as identity,
    name varchar(255),
    status integer,
    primary key (id)
);

drop table user_revision if exists;
create table user_revision (
    id bigint generated by default as identity,
    status_updated_at timestamp,
    status_updated_by bigint,
    updated_at timestamp,
    updated_by bigint,
    user_id bigint,
    primary key (id)
);